[package]
name = "controlmap-parser"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["SARDONYX"]

[dependencies]
anyhow = "1.0.53"
pest = "2.1.3"
pest_derive = "2.1.0"
indexmap = "1.8.0"

[lib]
name = "controlmap_parser"
edition = "2021"
