new_line = _{ "\n" | "\r\n" }
WHITESPACE = _{ " "}
DELIMITER = _{ "\t" | ","  }

char = _{ (ASCII_ALPHANUMERIC | "+" | "-" | "/" | WHITESPACE) }
string = _{ char+ }

event_name = @{ (!"//" ~ string) }
keycode = @{ string }
comment = @{ (!new_line ~ ANY)* }

comment_row = _{ "//" ~ comment }
row = _{ event_name ~ (DELIMITER ~ keycode)* ~ DELIMITER* }
blank_line = @{ (new_line | "\t")+ }

rows = _{
    SOI ~
    ((row | comment_row) ~ new_line? | blank_line)* ~
    EOI
}
